/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillRouteImport } from './routes/_layout/skill'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAppsAccountIdIndexRouteImport } from './routes/_layout/apps/$accountId/index'
import { Route as LayoutAuthenticatedSettingsIndexRouteImport } from './routes/_layout/_authenticated/settings/index'
import { Route as LayoutAuthenticatedProjectsIndexRouteImport } from './routes/_layout/_authenticated/projects/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutAppsAccountIdGatewayIdRouteImport } from './routes/_layout/apps/$accountId/$gatewayId'
import { Route as LayoutAuthenticatedSettingsSecurityRouteImport } from './routes/_layout/_authenticated/settings/security'
import { Route as LayoutAuthenticatedSettingsProfileRouteImport } from './routes/_layout/_authenticated/settings/profile'
import { Route as LayoutAuthenticatedSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/settings/auth-methods'
import { Route as LayoutAuthenticatedSettingsApiKeysRouteImport } from './routes/_layout/_authenticated/settings/api-keys'
import { Route as LayoutAuthenticatedProjectsNewRouteImport } from './routes/_layout/_authenticated/projects/new'
import { Route as LayoutAuthenticatedProjectsIdRouteImport } from './routes/_layout/_authenticated/projects/$id'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/organizations/$slug'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'
import { Route as LayoutAuthenticatedProjectsIdEditRouteImport } from './routes/_layout/_authenticated/projects/$id.edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRoute = LayoutSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAppsAccountIdIndexRoute =
  LayoutAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedSettingsIndexRoute =
  LayoutAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedProjectsIndexRoute =
  LayoutAuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAppsAccountIdGatewayIdRoute =
  LayoutAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedSettingsSecurityRoute =
  LayoutAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsProfileRoute =
  LayoutAuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsAuthMethodsRoute =
  LayoutAuthenticatedSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsApiKeysRoute =
  LayoutAuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedProjectsNewRoute =
  LayoutAuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProjectsIdRoute =
  LayoutAuthenticatedProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsSlugRoute =
  LayoutAuthenticatedOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProjectsIdEditRoute =
  LayoutAuthenticatedProjectsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutAuthenticatedProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/apps/': typeof LayoutAppsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/projects/$id': typeof LayoutAuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/projects/': typeof LayoutAuthenticatedProjectsIndexRoute
  '/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/projects/$id/edit': typeof LayoutAuthenticatedProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/projects/$id': typeof LayoutAuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/projects': typeof LayoutAuthenticatedProjectsIndexRoute
  '/settings': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps/$accountId': typeof LayoutAppsAccountIdIndexRoute
  '/projects/$id/edit': typeof LayoutAuthenticatedProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/skill': typeof LayoutSkillRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/projects/$id': typeof LayoutAuthenticatedProjectsIdRouteWithChildren
  '/_layout/_authenticated/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/_layout/_authenticated/settings/api-keys': typeof LayoutAuthenticatedSettingsApiKeysRoute
  '/_layout/_authenticated/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/_layout/_authenticated/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/_layout/_authenticated/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/_layout/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/projects/': typeof LayoutAuthenticatedProjectsIndexRoute
  '/_layout/_authenticated/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/_layout/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/_layout/_authenticated/projects/$id/edit': typeof LayoutAuthenticatedProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/skill'
    | '/home'
    | '/settings'
    | '/apps/'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/apps/$accountId/$gatewayId'
    | '/organizations/'
    | '/projects/'
    | '/settings/'
    | '/apps/$accountId/'
    | '/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/skill'
    | '/home'
    | '/apps'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/apps/$accountId/$gatewayId'
    | '/organizations'
    | '/projects'
    | '/settings'
    | '/apps/$accountId'
    | '/projects/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/login'
    | '/_layout/skill'
    | '/_layout/'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/settings'
    | '/_layout/apps/'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/organizations/$slug'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/projects/$id'
    | '/_layout/_authenticated/projects/new'
    | '/_layout/_authenticated/settings/api-keys'
    | '/_layout/_authenticated/settings/auth-methods'
    | '/_layout/_authenticated/settings/profile'
    | '/_layout/_authenticated/settings/security'
    | '/_layout/apps/$accountId/$gatewayId'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/projects/'
    | '/_layout/_authenticated/settings/'
    | '/_layout/apps/$accountId/'
    | '/_layout/_authenticated/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill': {
      id: '/_layout/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/apps/$accountId/': {
      id: '/_layout/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings/': {
      id: '/_layout/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/projects/': {
      id: '/_layout/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/apps/$accountId/$gatewayId': {
      id: '/_layout/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings/security': {
      id: '/_layout/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/profile': {
      id: '/_layout/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/auth-methods': {
      id: '/_layout/_authenticated/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/api-keys': {
      id: '/_layout/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/projects/new': {
      id: '/_layout/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/projects/$id': {
      id: '/_layout/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$slug': {
      id: '/_layout/_authenticated/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/projects/$id/edit': {
      id: '/_layout/_authenticated/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsIdEditRouteImport
      parentRoute: typeof LayoutAuthenticatedProjectsIdRoute
    }
  }
}

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsApiKeysRoute: typeof LayoutAuthenticatedSettingsApiKeysRoute
  LayoutAuthenticatedSettingsAuthMethodsRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  LayoutAuthenticatedSettingsProfileRoute: typeof LayoutAuthenticatedSettingsProfileRoute
  LayoutAuthenticatedSettingsSecurityRoute: typeof LayoutAuthenticatedSettingsSecurityRoute
  LayoutAuthenticatedSettingsIndexRoute: typeof LayoutAuthenticatedSettingsIndexRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsApiKeysRoute:
      LayoutAuthenticatedSettingsApiKeysRoute,
    LayoutAuthenticatedSettingsAuthMethodsRoute:
      LayoutAuthenticatedSettingsAuthMethodsRoute,
    LayoutAuthenticatedSettingsProfileRoute:
      LayoutAuthenticatedSettingsProfileRoute,
    LayoutAuthenticatedSettingsSecurityRoute:
      LayoutAuthenticatedSettingsSecurityRoute,
    LayoutAuthenticatedSettingsIndexRoute:
      LayoutAuthenticatedSettingsIndexRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedProjectsIdRouteChildren {
  LayoutAuthenticatedProjectsIdEditRoute: typeof LayoutAuthenticatedProjectsIdEditRoute
}

const LayoutAuthenticatedProjectsIdRouteChildren: LayoutAuthenticatedProjectsIdRouteChildren =
  {
    LayoutAuthenticatedProjectsIdEditRoute:
      LayoutAuthenticatedProjectsIdEditRoute,
  }

const LayoutAuthenticatedProjectsIdRouteWithChildren =
  LayoutAuthenticatedProjectsIdRoute._addFileChildren(
    LayoutAuthenticatedProjectsIdRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
  LayoutAuthenticatedOrganizationsSlugRoute: typeof LayoutAuthenticatedOrganizationsSlugRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedProjectsIdRoute: typeof LayoutAuthenticatedProjectsIdRouteWithChildren
  LayoutAuthenticatedProjectsNewRoute: typeof LayoutAuthenticatedProjectsNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
  LayoutAuthenticatedProjectsIndexRoute: typeof LayoutAuthenticatedProjectsIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
  LayoutAuthenticatedOrganizationsSlugRoute:
    LayoutAuthenticatedOrganizationsSlugRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedProjectsIdRoute:
    LayoutAuthenticatedProjectsIdRouteWithChildren,
  LayoutAuthenticatedProjectsNewRoute: LayoutAuthenticatedProjectsNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
  LayoutAuthenticatedProjectsIndexRoute: LayoutAuthenticatedProjectsIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSkillRoute: typeof LayoutSkillRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutAppsAccountIdGatewayIdRoute: typeof LayoutAppsAccountIdGatewayIdRoute
  LayoutAppsAccountIdIndexRoute: typeof LayoutAppsAccountIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSkillRoute: LayoutSkillRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutAppsAccountIdGatewayIdRoute: LayoutAppsAccountIdGatewayIdRoute,
  LayoutAppsAccountIdIndexRoute: LayoutAppsAccountIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
