import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { DeployConfig, InfraConfig } from "./types";

export interface AlchemyRunSpec {
  provider: "railway" | "alchemy";
  service?: string;
  neonProject?: string;
  stage: "production" | "staging" | "preview";
}

export function generateAlchemyRun(
  deployConfig: DeployConfig,
  infraConfig: InfraConfig | undefined,
  projectDir: string,
  stage: AlchemyRunSpec["stage"] = "production",
): void {
  const spec: AlchemyRunSpec = {
    provider: deployConfig.provider,
    service: deployConfig.service,
    neonProject: process.env.NEON_PROJECT ?? "everything-dev",
    stage,
  };

  const script = generateScript(spec, infraConfig);
  const outPath = resolve(join(projectDir, "alchemy.run.ts"));
  writeFileSync(outPath, script);
}

function generateScript(spec: AlchemyRunSpec, infraConfig: InfraConfig | undefined): string {
  const lines: string[] = [
    "// Generated by `bos deploy` — do not edit manually",
    "// To regenerate: update [deploy] in bos.config.toml and run `bos deploy`",
    "",
    `const provider = "${spec.provider}";`,
    `const stage = "${spec.stage}";`,
  ];

  if (spec.service) {
    lines.push(`const service = "${spec.service}";`);
  }

  if (spec.provider === "alchemy") {
    lines.push(`const neonProject = "${spec.neonProject}";`);
    lines.push("");
    lines.push("// Steps:");
    lines.push("// 1. Drizzle.Schema: generate migrations from schema files");
    lines.push("// 2. Neon.Branch: create/get branch for stage, apply migrations");
    lines.push("// 3. Set DATABASE_URL = branch pooled connection URI");
    lines.push("// 4. Deploy MF remotes to Zephyr CDN");
    lines.push("// 5. Redeploy host container with new DATABASE_URL");
  }

  if (infraConfig?.database) {
    lines.push("");
    lines.push("// Database isolation handled via search_path at the driver layer");
  }

  if (spec.provider === "railway") {
    lines.push("");
    lines.push("// Railway deployment:");
    if (spec.service) {
      lines.push(`// Redeploy service: ${spec.service}`);
    } else {
      lines.push("// No service configured — set [deploy].service in bos.config.toml");
    }
  }

  lines.push("");
  lines.push(`export default { provider: "${spec.provider}", stage: "${spec.stage}" };`);

  return `${lines.join("\n")}\n`;
}
