// Generated by manifest-gen. DO NOT EDIT.
// Inputs: src/routes/** only.
import type { RouteConfigModule, RouteOptionsBundle } from "@manifest-compose/shared";

const pick = (o: any): RouteOptionsBundle => ({
  loader: o?.loader,
  beforeLoad: o?.beforeLoad,
  head: o?.head,
  staticData: o?.staticData,
  component: o?.component,
  errorComponent: o?.errorComponent,
  pendingComponent: o?.pendingComponent,
  notFoundComponent: o?.notFoundComponent,
});

import { Route as __rootRoute } from "./routes/__root";

export const routeConfigLoaders: RouteConfigModule["routeConfigLoaders"] = {
  "_authenticated": () => import("./routes/_authenticated").then((m) => pick(m.Route.options)),
  "_public": () => import("./routes/_public").then((m) => pick(m.Route.options)),
  "_authenticated/settings": () => import("./routes/_authenticated/settings").then((m) => pick(m.Route.options)),
  "_public/login": () => import("./routes/_public/login").then((m) => pick(m.Route.options)),
  "_authenticated/settings/api-keys": () => import("./routes/_authenticated/settings/api-keys").then((m) => pick(m.Route.options)),
};

export const rootMeta = pick(__rootRoute.options);
